version: "3"

services:
  api:
    env_file:
      - .env
    restart: always
    build: ./api
    working_dir: /api
    volumes:
    - ./api:/api
    expose:
      - "8000"
    ports:
      - "8000:8000"
    depends_on:
      - redis
    command: gunicorn app:app -b :8000 --name app --log-level=debug --workers=2 --threads=4 --log-file=-

  frontend:
    build: ./frontend
    image: frontend:latest
    env_file:
      - ./frontend/.env
    command: bash -c "npm install && npm start"
    volumes:
      - ./frontend:/frontend
    ports:
      - "8080:8080"

  redis:
     image: redis

  server:
    restart: always
    image: nginx
    volumes:
      - .:/www/static
      - ./server/conf.d:/etc/nginx/conf.d
      - ./app/static:/app/static
      - nginx-logs:/etc/nginx/logs/:rw
    links:
      - frontend:frontend
      - api:api
    ports:
      - "80:80"
      - "4000:4000"
    depends_on:
      - redis

volumes:
  nginx-logs:
